<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-1P383OOE" failures="1" tests="4" name="edgeTest" time="44.325" errors="0" timestamp="2025-04-14T15:56:05 IST">
  <testcase classname="testCases.TC_Invalid_Valid_Login_Credentials" name="Invalid_Email" time="1.487"/>
  <testcase classname="testCases.TC_Invalid_Valid_Login_Credentials" name="Invalid_Password" time="1.889"/>
  <testcase classname="testCases.TC_Invalid_Valid_Login_Credentials" name="valid_Credentials" time="1.981"/>
  <testcase classname="testCases.TC_MedicareSignup" name="Verify_MedicarSignUP" time="17.862">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC_MedicareSignup.Verify_MedicarSignUP(TC_MedicareSignup.java:115)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Verify_MedicarSignUP -->
</testsuite> <!-- edgeTest -->
